import {canPerformOrganizationAction, normalizeOrganizationRole, organizationSectionsForRole} from './access.js'
import {ORGANIZATION_SECTION_ORDER, ORGANIZATION_SECTIONS} from './fields.js'
import {renderOrganizationNav} from './layout.js'
import {renderOrganizationSections} from './sections.js'
import {readOrganizationSessionState} from './sessions.js'

const SETTINGS_KEY = 'skey-proto-organization-settings'

// Maps each data-list-backed section key to its DATA_LIST_CONFIG context
// and the canvas/fnav element id pair sections.js's dataListMount()
// renders (concepts/app/pages/organization/sections.js).
const TABLE_SECTIONS = {
  users: {context: 'orgUsers', mount: 'users'},
  'application-sessions': {context: 'orgAppSessions', mount: 'app-sessions'},
  'database-sessions': {context: 'orgDbSessions', mount: 'db-sessions'},
  audit: {context: 'orgAudit', mount: 'audit'},
  staff: {context: 'orgStaff', mount: 'staff'},
}

function readObject(storage, key) {
  try {
    const value = JSON.parse(storage.getItem(key) || '{}')
    return value && !Array.isArray(value) && typeof value === 'object' ? value : {}
  } catch {
    return {}
  }
}

export function createOrganization({
  root,
  role = 'administrator',
  fixtures,
  storage,
  toast,
  encodeHtml,
  dataListIcon,
  dataListInstances,
  onAccessDenied = () => {},
  createSessionActions,
  trapFocus,
  releaseFocus,
}) {
  const navMount = root.querySelector('#organization-nav-mount')
  const contentMount = root.querySelector('#organization-content')
  const roleBadge = root.querySelector('#organization-role-badge')
  let activeRole = normalizeOrganizationRole(role)
  let activeSection = 'overview'
  let rendered = false
  let sessionActions = null
  let settings = {...fixtures.details, ...readObject(storage, SETTINGS_KEY)}

  const scoped = rows => activeRole === 'manager' ? rows.filter(row => row.inManagerScope) : rows

  function getData() {
    const sessionState = readOrganizationSessionState(storage)
    const applicationSessions = scoped(fixtures.applicationSessions.filter(row => !sessionState.revokedApplicationIds.includes(row.id)))
      .map(row => ({...row, canRevoke: canPerformOrganizationAction(activeRole, 'revoke-session', row)}))
    const databaseSessions = fixtures.databaseSessions.filter(row => !sessionState.terminatedDatabaseIds.includes(row.id))
      .map(row => ({...row, canTerminate: canPerformOrganizationAction(activeRole, 'terminate-database-session', row)}))
    return {
      details: settings,
      users: scoped(fixtures.users),
      applicationSessions,
      databaseSessions,
      auditRows: scoped([...sessionState.auditEvents, ...fixtures.auditRows]),
      staff: scoped(fixtures.staff),
      health: fixtures.health,
      services: fixtures.services,
    }
  }

  // Feeds each data-list-backed section's fresh, role-scoped rows into its
  // engine instance (model.js's setRows — see that file's comment for why
  // this dynamic-rows mechanism exists). Called on every render() (role
  // change, session mutation) since the row sets themselves may have
  // changed; activation is handled separately by activateTableSection,
  // since #organization-content isn't regenerated on a plain tab switch.
  function setTableRows(data) {
    const rowsByContext = {
      orgUsers: data.users,
      orgAppSessions: data.applicationSessions,
      orgDbSessions: data.databaseSessions,
      orgAudit: data.auditRows,
      orgStaff: data.staff,
    }
    Object.values(TABLE_SECTIONS).forEach(({context}) => dataListInstances[context]?.setRows(rowsByContext[context]))
  }

  // Activates the given section's data-list instance against its
  // canvas/fnav (a no-op if `key` isn't table-backed) and deactivates
  // every other table-backed section's instance, so an inactive section
  // never keeps a stale/hidden-canvas reference alive. #organization-
  // content is only regenerated by render() (role change / full
  // re-render) — a plain tab switch via setActivePanel just toggles
  // `hidden` on already-rendered sibling panels — so this must run on
  // both paths for the newly-visible table to actually mount.
  function activateTableSection(key) {
    const table = TABLE_SECTIONS[key]
    Object.entries(TABLE_SECTIONS).forEach(([sectionKey, {context, mount}]) => {
      const instance = dataListInstances[context]
      if (!instance) return
      if (sectionKey === key) {
        const canvas = root.querySelector(`#organization-${mount}-canvas`)
        const footer = root.querySelector(`#organization-${mount}-fnav`)
        if (canvas) instance.activate({root: canvas, footer})
      } else {
        instance.deactivate()
      }
    })
    return table
  }

  function setActivePanel(key) {
    const allowed = organizationSectionsForRole(activeRole)
    if (!allowed.includes(key)) return
    activeSection = key
    root.querySelectorAll('[data-organization-section]').forEach(button => {
      const current = button.dataset.organizationSection === key
      button.setAttribute('aria-current', current ? 'page' : 'false')
      button.tabIndex = current ? 0 : -1
    })
    root.querySelectorAll('[data-organization-panel]').forEach(panel => {
      panel.hidden = panel.dataset.organizationPanel !== key
    })
    activateTableSection(key)
  }

  function bindSettings() {
    if (activeRole !== 'administrator') return
    const controls = [...root.querySelectorAll('[data-organization-setting]')]
    const save = root.querySelector('#organization-settings-save')
    const undo = root.querySelector('#organization-settings-undo')
    if (!save || !undo) return
    const setDirty = dirty => {
      save.disabled = !dirty
      undo.disabled = !dirty
    }
    const restore = () => {
      controls.forEach(control => { control.value = settings[control.dataset.organizationSetting] })
      setDirty(false)
    }
    controls.forEach(control => control.addEventListener('input', () => setDirty(true)))
    undo.addEventListener('click', restore)
    save.addEventListener('click', () => {
      settings = Object.fromEntries(controls.map(control => [control.dataset.organizationSetting, control.value.trim()]))
      storage.setItem(SETTINGS_KEY, JSON.stringify(settings))
      setDirty(false)
      toast({tone: 'ok', title: 'Organization settings saved'})
    })
  }

  function bindAuditExport() {
    root.querySelector('[data-organization-export-audit]')?.addEventListener('click', () => {
      const rows = getData().auditRows
      const escape = value => `"${String(value).replaceAll('"', '""')}"`
      const csv = [['Timestamp', 'Actor', 'Action', 'Object', 'Source', 'Result'], ...rows.map(row => [row.timestamp, row.actor, row.action, row.object, row.source, row.result])]
        .map(row => row.map(escape).join(','))
        .join('\n')
      const link = document.createElement('a')
      link.href = URL.createObjectURL(new Blob([csv], {type: 'text/csv'}))
      link.download = 'skey-organization-audit.csv'
      link.click()
      URL.revokeObjectURL(link.href)
      toast({tone: 'ok', title: 'Audit log exported'})
    })
  }

  function bind() {
    navMount.querySelectorAll('[data-organization-section]').forEach(button => {
      button.addEventListener('click', () => setActivePanel(button.dataset.organizationSection))
    })
    contentMount.querySelectorAll('[data-organization-open-section]').forEach(button => {
      button.addEventListener('click', () => setActivePanel(button.dataset.organizationOpenSection))
    })
    bindSettings()
    bindAuditExport()
    sessionActions?.dispose()
    sessionActions = createSessionActions?.({
      root,
      role: activeRole,
      data: getData(),
      storage,
      toast,
      encodeHtml,
      rerender: render,
      trapFocus,
      releaseFocus,
    })
    sessionActions?.bind()
  }

  navMount.addEventListener('keydown', event => {
    const tab = event.target.closest('[data-organization-section]')
    if (!tab || !['ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return
    event.preventDefault()
    const tabs = [...navMount.querySelectorAll('[data-organization-section]')]
    const index = tabs.indexOf(tab)
    const nextIndex =
      event.key === 'Home'
        ? 0
        : event.key === 'End'
          ? tabs.length - 1
          : event.key === 'ArrowUp'
            ? (index - 1 + tabs.length) % tabs.length
            : (index + 1) % tabs.length
    tabs[nextIndex].focus()
    tabs[nextIndex].click()
  })

  function render() {
    const sections = organizationSectionsForRole(activeRole)
    if (!sections.length) return
    if (!sections.includes(activeSection)) activeSection = 'overview'
    roleBadge.textContent = activeRole === 'administrator' ? 'Administrator' : 'Manager · restricted'
    navMount.innerHTML = renderOrganizationNav(sections, ORGANIZATION_SECTIONS, activeSection, encodeHtml)
    const data = getData()
    contentMount.innerHTML = renderOrganizationSections({
      sectionOrder: sections,
      sections: ORGANIZATION_SECTIONS,
      role: activeRole,
      data,
      activeKey: activeSection,
      encodeHtml,
      dataListIcon,
    })
    setTableRows(data)
    activateTableSection(activeSection)
    bind()
    rendered = true
  }

  function setSection(key) {
    if (!rendered) activeSection = key
    else setActivePanel(key)
  }

  function setRole(nextRole) {
    activeRole = normalizeOrganizationRole(nextRole)
    if (activeRole === 'user') {
      onAccessDenied()
      return
    }
    if (rendered) render()
  }

  function activate({section} = {}) {
    if (activeRole === 'user') {
      onAccessDenied()
      return
    }
    if (section) activeSection = section
    render()
  }

  function deactivate() {
    sessionActions?.dispose()
    Object.values(TABLE_SECTIONS).forEach(({context}) => dataListInstances[context]?.deactivate())
  }

  function dispose() {
    deactivate()
    rendered = false
  }

  return {id: 'organization', roots: {root}, activate, deactivate, dispose, setRole, setSection}
}

export {ORGANIZATION_SECTION_ORDER}
